# Generated by Django 2.2.6 on 2019-10-20 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helmet_zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helmet_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
