# Generated by Django 2.2.6 on 2019-10-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helmet_zones', '0002_bookingcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcount',
            name='is_scooter_rented',
            field=models.BooleanField(default=False),
        ),
    ]
